import type { Experience } from './types';

export const experiences: Experience[] = [
  // Canada (7)
  {
    id: 1,
    title: "The Honored One",
    company: "Gojo Clan Heritage",
    location: "Canada",
    duration: "Birthright",
    description: [
        "Inherited the legendary Six Eyes and the Limitless cursed technique.",
        "Mastered Reverse Cursed Technique and Domain Expansion at an unprecedented age.",
        "Single-handedly shifted the balance of the entire Jujutsu world.",
    ],
    position: { top: '15%', left: '50%' },
  },
  {
    id: 4,
    title: "Barrier Technique Instructor",
    company: "Jujutsu High Curriculum",
    location: "Canada",
    duration: "Ongoing",
    description: [
        "Educated students on the complex principles of barrier techniques and domain creation.",
        "Developed custom training regimens to strengthen students' defensive capabilities.",
        "Consulted on the reinforcement of the protective barriers around Jujutsu High.",
    ],
    position: { top: '35%', left: '30%' },
  },
  {
    id: 6,
    title: "Curse Exorcism Specialist",
    company: "Kyoto Jujutsu High (Exchange)",
    location: "Canada",
    duration: "2020 Exchange Program",
    description: [
      "Led joint exorcism missions with Kyoto students during the annual Goodwill Event.",
      "Developed advanced barrier techniques to contain and analyze curse energy signatures.",
      "Provided critical analysis on the Cursed Womb: Death Painting brothers.",
    ],
    position: { top: '68%', left: '18%' },
  },
  {
    id: 9,
    title: "International Curse Recon",
    company: "Global Sorcerer Alliance",
    location: "Canada",
    duration: "Periodic Missions",
    description: [
        "Traveled abroad to investigate and neutralize unique cursed spirit phenomena.",
        "Established cooperative channels with international sorcerer organizations.",
        "Gathered intelligence on the global network of curse users.",
    ],
    position: { top: '55%', left: '80%' },
  },
   {
    id: 11,
    title: "Reverse Cursed Technique Adept",
    company: "Self-Taught",
    location: "Canada",
    duration: "2006 - Present",
    description: [
        "Mastered the rare ability to convert negative cursed energy into positive energy.",
        "Capable of regenerating from fatal wounds and maintaining peak physical condition.",
        "Applied positive energy offensively to create 'Red' and 'Hollow Purple'.",
    ],
    position: { top: '25%', left: '8%' },
  },
  {
    id: 12,
    title: "Six Eyes Operator",
    company: "Gojo Clan",
    location: "Canada",
    duration: "Inherited",
    description: [
      "Utilized the Six Eyes to perceive cursed energy with unparalleled detail and efficiency.",
      "Managed cursed energy reserves to maintain combat readiness for extended periods.",
      "Acted as the primary deterrent against major threats from curse user factions.",
    ],
    position: { top: '88%', left: '55%' },
  },
  {
    id: 14,
    title: "Cursed Energy Theorist",
    company: "Jujutsu Research Division",
    location: "Canada",
    duration: "Consultant",
    description: [
      "Published influential research on the nature of Cursed Energy and its applications.",
      "Theorized the possibility of non-standard Domain Expansions.",
      "Mentored a new generation of Jujutsu researchers on ethical experimentation.",
    ],
    position: { top: '45%', left: '60%' },
  },
  
  // Malaysia (5)
  {
    id: 2,
    title: "Special Grade Sorcerer",
    company: "Tokyo Jujutsu High",
    location: "Malaysia",
    duration: "2018 - Present",
    description: [
      "Mentored promising students like Yuji Itadori, Megumi Fushiguro, and Nobara Kugisaki.",
      "Neutralized numerous special-grade cursed spirits, including Jogo and Hanami.",
      "Pioneered new applications of the Limitless, including 'Hollow Purple'.",
    ],
    position: { top: '20%', left: '90%' },
  },
  {
    id: 5,
    title: "Shibuya Incident Commander",
    company: "Jujutsu High Command",
    location: "Malaysia",
    duration: "Oct 2018",
    description: [
      "Served as the vanguard force during the Shibuya Incident, neutralizing multiple threats.",
      "Protected civilians from Mahito's transfiguration using a 0.2-second 'Unlimited Void'.",
      "Was ultimately sealed within the Prison Realm after a strategic confrontation.",
    ],
    position: { top: '75%', left: '78%' },
  },
  {
    id: 7,
    title: "Domain Expansion Researcher",
    company: "Jujutsu Tech R&D",
    location: "Malaysia",
    duration: "2019 - 2021",
    description: [
      "Authored a foundational paper on the theoretical limits of 'Unlimited Void'.",
      "Consulted on the development of anti-domain countermeasures for Grade 1 sorcerers.",
      "Analyzed the domain structures of opponents to devise effective strategies.",
    ],
    position: { top: '40%', left: '5%' },
  },
  {
    id: 10,
    title: "Jujutsu Archive Curator",
    company: "Gojo Family Vaults",
    location: "Malaysia",
    duration: "Ongoing",
    description: [
        "Oversaw the preservation of ancient texts and artifacts detailing Gojo clan techniques.",
        "Deciphered complex cursed energy patterns from historical records using the Six Eyes.",
        "Ensured the security of forbidden knowledge against rogue elements.",
    ],
    position: { top: '92%', left: '30%' },
  },
  {
    id: 13,
    title: "Youth Mentor",
    company: "Jujutsu Outreach Program",
    location: "Malaysia",
    duration: "Volunteer",
    description: [
      "Provided guidance to young, newly-awakened sorcerers outside the official Jujutsu High system.",
      "Developed safe training programs for controlling innate cursed energy.",
      "Acted as a positive role model to prevent youths from being exploited by curse users.",
    ],
    position: { top: '5%', left: '20%' },
  },
  
  // Bangladesh (2)
  {
    id: 3,
    title: "Star Plasma Vessel Escort",
    company: "Jujutsu High Assignment",
    location: "Bangladesh",
    duration: "2006",
    description: [
        "Tasked with the critical mission of protecting the Star Plasma Vessel, Riko Amanai.",
        "Engaged in a prolonged battle against the Sorcerer Killer, Toji Fushiguro.",
        "Unlocked the Reverse Cursed Technique under extreme duress.",
    ],
    position: { top: '60%', left: '42%' },
  },
  {
    id: 8,
    title: "Cursed Tool Appraiser",
    company: "Jujutsu High Armory",
    location: "Bangladesh",
    duration: "Consultant",
    description: [
        "Utilized the Six Eyes to accurately assess the flow and power of cursed energy within tools.",
        "Authenticated and cataloged newly discovered cursed objects for the Jujutsu High vaults.",
        "Advised on appropriate user pairings for powerful weapons like the Inverted Spear of Heaven.",
    ],
    position: { top: '80%', left: '95%' },
  },
];
